// Jal Drishti — Uttarakhand Terrain Intelligence
// Geographic data for the interactive terrain map.
// Monitoring station readings are SIMULATION DATA until connected to a live backend.

// ── Uttarakhand map configuration ────────────────────────────────────────────
export const UK_CENTER = [30.1, 79.2];
export const UK_ZOOM   = 7;
export const UK_BOUNDS = [[28.7, 77.5], [31.5, 81.1]];

// ── Monitoring stations ───────────────────────────────────────────────────────
// status: 'NORMAL' | 'WATCH' | 'ELEVATED' | 'CRITICAL'
export const MONITORING_STATIONS = [
  {
    id: 'dehradun',
    name: 'Dehradun',
    lat: 30.3165,
    lng: 78.0322,
    elevation: 640,
    district: 'Dehradun',
    basin: 'Ganga',
    river: 'Rispana / Bindal',
    status: 'NORMAL',
    rainfall_mm: 28,
    river_level: 'Normal',
    slope_risk: 'Moderate',
    flood_risk: 'Low',
  },
  {
    id: 'haridwar',
    name: 'Haridwar',
    lat: 29.9457,
    lng: 78.1642,
    elevation: 314,
    district: 'Haridwar',
    basin: 'Ganga',
    river: 'Ganga',
    status: 'WATCH',
    rainfall_mm: 52,
    river_level: 'Elevated',
    slope_risk: 'Low',
    flood_risk: 'Moderate',
  },
  {
    id: 'rishikesh',
    name: 'Rishikesh',
    lat: 30.0869,
    lng: 78.2676,
    elevation: 356,
    district: 'Dehradun',
    basin: 'Ganga',
    river: 'Ganga',
    status: 'WATCH',
    rainfall_mm: 44,
    river_level: 'Normal',
    slope_risk: 'Moderate',
    flood_risk: 'Low',
  },
  {
    id: 'joshimath',
    name: 'Joshimath',
    lat: 30.5594,
    lng: 79.5641,
    elevation: 1875,
    district: 'Chamoli',
    basin: 'Alaknanda',
    river: 'Alaknanda',
    status: 'ELEVATED',
    rainfall_mm: 68,
    river_level: 'Elevated',
    slope_risk: 'High',
    flood_risk: 'Moderate',
  },
  {
    id: 'chamoli',
    name: 'Chamoli',
    lat: 30.4200,
    lng: 79.3300,
    elevation: 1070,
    district: 'Chamoli',
    basin: 'Alaknanda',
    river: 'Alaknanda',
    status: 'WATCH',
    rainfall_mm: 58,
    river_level: 'Elevated',
    slope_risk: 'High',
    flood_risk: 'Moderate',
  },
  {
    id: 'rudraprayag',
    name: 'Rudraprayag',
    lat: 30.2855,
    lng: 78.9776,
    elevation: 895,
    district: 'Rudraprayag',
    basin: 'Alaknanda',
    river: 'Alaknanda / Mandakini',
    status: 'WATCH',
    rainfall_mm: 61,
    river_level: 'Elevated',
    slope_risk: 'High',
    flood_risk: 'Moderate',
  },
  {
    id: 'srinagar_uk',
    name: 'Srinagar (Garhwal)',
    lat: 30.2204,
    lng: 78.7830,
    elevation: 560,
    district: 'Pauri Garhwal',
    basin: 'Alaknanda',
    river: 'Alaknanda',
    status: 'NORMAL',
    rainfall_mm: 35,
    river_level: 'Normal',
    slope_risk: 'Moderate',
    flood_risk: 'Low',
  },
  {
    id: 'uttarkashi',
    name: 'Uttarkashi',
    lat: 30.7268,
    lng: 78.4354,
    elevation: 1158,
    district: 'Uttarkashi',
    basin: 'Bhagirathi',
    river: 'Bhagirathi',
    status: 'NORMAL',
    rainfall_mm: 40,
    river_level: 'Normal',
    slope_risk: 'High',
    flood_risk: 'Low',
  },
  {
    id: 'tehri',
    name: 'Tehri',
    lat: 30.3780,
    lng: 78.4802,
    elevation: 770,
    district: 'Tehri Garhwal',
    basin: 'Bhagirathi / Bhilangna',
    river: 'Bhilangna',
    status: 'NORMAL',
    rainfall_mm: 32,
    river_level: 'Normal',
    slope_risk: 'High',
    flood_risk: 'Low',
  },
  {
    id: 'pithoragarh',
    name: 'Pithoragarh',
    lat: 29.5831,
    lng: 80.2181,
    elevation: 1814,
    district: 'Pithoragarh',
    basin: 'Sharda / Kali',
    river: 'Kali (Mahakali)',
    status: 'ELEVATED',
    rainfall_mm: 74,
    river_level: 'Elevated',
    slope_risk: 'High',
    flood_risk: 'High',
  },
  {
    id: 'haldwani',
    name: 'Haldwani',
    lat: 29.2183,
    lng: 79.5130,
    elevation: 424,
    district: 'Nainital',
    basin: 'Ramganga',
    river: 'Gaula',
    status: 'CRITICAL',
    rainfall_mm: 98,
    river_level: 'Danger Zone',
    slope_risk: 'Low',
    flood_risk: 'High',
  },
];

// ── Status configuration ──────────────────────────────────────────────────────
export const STATUS_CONFIG = {
  NORMAL:   { color: '#10B981', label: 'Normal',   ring: '#10B981' },
  WATCH:    { color: '#F59E0B', label: 'Watch',    ring: '#F59E0B' },
  ELEVATED: { color: '#F97316', label: 'Elevated', ring: '#F97316' },
  CRITICAL: { color: '#EF4444', label: 'Critical', ring: '#EF4444' },
};

// ── Tile layer definitions ─────────────────────────────────────────────────────
export const TILE_LAYERS = {
  satellite: {
    label: 'Satellite',
    url: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
    attribution: 'Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community',
    maxZoom: 17,
  },
  terrain: {
    label: 'Terrain',
    url: 'https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',
    attribution: 'Map data: &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, <a href="http://viewfinderpanoramas.org">SRTM</a> | Map style: &copy; <a href="https://opentopomap.org">OpenTopoMap</a>',
    maxZoom: 15,
  },
  dark: {
    label: 'Dark',
    url: `https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png${import.meta.env.VITE_CARTO_API_KEY && import.meta.env.VITE_CARTO_API_KEY !== 'cb1_2k56_1_d8f949035bf0414f5da8a77b' ? `?key=${import.meta.env.VITE_CARTO_API_KEY}` : ''}`,
    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>',
    maxZoom: 19,
  },
};
