"""Add SachetAlert model

Revision ID: 111717eb5262
Revises: 002_risk_decision_engine
Create Date: 2026-09-27 02:52:33.054382

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '111717eb5262'
down_revision: Union[str, None] = '002_risk_decision_engine'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sachet_alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('sent', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('msg_type', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('event', sa.String(), nullable=True),
    sa.Column('urgency', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('certainty', sa.String(), nullable=True),
    sa.Column('onset', sa.DateTime(), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.Column('area_description', sa.Text(), nullable=True),
    sa.Column('polygon', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('raw_xml', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_sachet_alerts_polygon', 'sachet_alerts', ['polygon'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_sachet_alerts_id'), 'sachet_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_sachet_alerts_identifier'), 'sachet_alerts', ['identifier'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    pass
    op.drop_index(op.f('flood_predictions_timestamp_utc_idx'), table_name='flood_predictions')
    op.drop_constraint(op.f('uq_flood_predictions_sample_id'), 'flood_predictions', type_='unique')
    op.create_index('idx_predictions_geom', 'flood_predictions', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('idx_predictions_risk_district', 'flood_predictions', ['district', 'ml_risk_class'], unique=False)
    op.create_index('idx_predictions_time_spatial', 'flood_predictions', ['timestamp_utc', 'spatial_id'], unique=False)
    op.create_index(op.f('ix_flood_predictions_district'), 'flood_predictions', ['district'], unique=False)
    op.create_index(op.f('ix_flood_predictions_ml_risk_class'), 'flood_predictions', ['ml_risk_class'], unique=False)
    op.create_index(op.f('ix_flood_predictions_prediction_probability'), 'flood_predictions', ['prediction_probability'], unique=False)
    op.create_index(op.f('ix_flood_predictions_sample_type'), 'flood_predictions', ['sample_type'], unique=False)
    op.create_index(op.f('ix_flood_predictions_spatial_id'), 'flood_predictions', ['spatial_id'], unique=False)
    op.create_index(op.f('ix_flood_predictions_timestamp_utc'), 'flood_predictions', ['timestamp_utc'], unique=False)
    op.create_index('idx_hist_events_district_type', 'historical_flood_events', ['district', 'event_type'], unique=False)
    op.create_index('idx_hist_events_geom', 'historical_flood_events', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_historical_flood_events_district'), 'historical_flood_events', ['district'], unique=False)
    op.create_index(op.f('ix_historical_flood_events_event_date'), 'historical_flood_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_historical_flood_events_event_id'), 'historical_flood_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_historical_flood_events_event_type'), 'historical_flood_events', ['event_type'], unique=False)
    op.drop_index(op.f('rainfall_observations_timestamp_utc_idx'), table_name='rainfall_observations')
    op.create_index('idx_rain_obs_district', 'rainfall_observations', ['district'], unique=False)
    op.create_index('idx_rain_obs_geom', 'rainfall_observations', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('idx_rain_obs_time_spatial', 'rainfall_observations', ['timestamp_utc', 'spatial_id'], unique=False)
    op.create_index(op.f('ix_rainfall_observations_district'), 'rainfall_observations', ['district'], unique=False)
    op.create_index(op.f('ix_rainfall_observations_spatial_id'), 'rainfall_observations', ['spatial_id'], unique=False)
    op.create_index(op.f('ix_rainfall_observations_timestamp_utc'), 'rainfall_observations', ['timestamp_utc'], unique=False)
    op.drop_index(op.f('risk_decisions_timestamp_utc_idx'), table_name='risk_decisions')
    op.drop_constraint(op.f('uq_risk_decisions_sample_id'), 'risk_decisions', type_='unique')
    op.create_index(op.f('ix_risk_decisions_alert_priority'), 'risk_decisions', ['alert_priority'], unique=False)
    op.create_index(op.f('ix_risk_decisions_district'), 'risk_decisions', ['district'], unique=False)
    op.create_index(op.f('ix_risk_decisions_final_risk_class'), 'risk_decisions', ['final_risk_class'], unique=False)
    op.create_index(op.f('ix_risk_decisions_sample_id'), 'risk_decisions', ['sample_id'], unique=False)
    op.create_index(op.f('ix_risk_decisions_sample_type'), 'risk_decisions', ['sample_type'], unique=False)
    op.create_index(op.f('ix_risk_decisions_station_id'), 'risk_decisions', ['station_id'], unique=False)
    op.drop_index(op.f('soil_moisture_observations_timestamp_utc_idx'), table_name='soil_moisture_observations')
    op.create_index('idx_soil_obs_geom', 'soil_moisture_observations', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('idx_soil_obs_time_spatial', 'soil_moisture_observations', ['timestamp_utc', 'spatial_id'], unique=False)
    op.create_index(op.f('ix_soil_moisture_observations_spatial_id'), 'soil_moisture_observations', ['spatial_id'], unique=False)
    op.create_index(op.f('ix_soil_moisture_observations_timestamp_utc'), 'soil_moisture_observations', ['timestamp_utc'], unique=False)
    op.create_index(op.f('ix_stations_district'), 'stations', ['district'], unique=False)
    op.create_index(op.f('ix_stations_major_basin'), 'stations', ['major_basin'], unique=False)
    op.create_index(op.f('ix_stations_river_name'), 'stations', ['river_name'], unique=False)
    op.create_index(op.f('ix_stations_station_id'), 'stations', ['station_id'], unique=False)
    op.create_index(op.f('ix_stations_station_type'), 'stations', ['station_type'], unique=False)
    op.drop_index(op.f('water_level_observations_timestamp_utc_idx'), table_name='water_level_observations')
    op.create_index('idx_water_obs_alert', 'water_level_observations', ['official_alert_stage'], unique=False)
    op.create_index('idx_water_obs_time_station', 'water_level_observations', ['timestamp_utc', 'station_id'], unique=False)
    op.create_index(op.f('ix_water_level_observations_district'), 'water_level_observations', ['district'], unique=False)
    op.create_index(op.f('ix_water_level_observations_river_name'), 'water_level_observations', ['river_name'], unique=False)
    op.create_index(op.f('ix_water_level_observations_station_id'), 'water_level_observations', ['station_id'], unique=False)
    op.create_index(op.f('ix_water_level_observations_timestamp_utc'), 'water_level_observations', ['timestamp_utc'], unique=False)
    op.drop_index(op.f('weather_observations_timestamp_utc_idx'), table_name='weather_observations')
    op.create_index('idx_weather_obs_district', 'weather_observations', ['district'], unique=False)
    op.create_index('idx_weather_obs_geom', 'weather_observations', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('idx_weather_obs_time_station', 'weather_observations', ['timestamp_utc', 'station_id'], unique=False)
    op.create_index(op.f('ix_weather_observations_district'), 'weather_observations', ['district'], unique=False)
    op.create_index(op.f('ix_weather_observations_station_id'), 'weather_observations', ['station_id'], unique=False)
    op.create_index(op.f('ix_weather_observations_timestamp_utc'), 'weather_observations', ['timestamp_utc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_observations_timestamp_utc'), table_name='weather_observations')
    op.drop_index(op.f('ix_weather_observations_station_id'), table_name='weather_observations')
    op.drop_index(op.f('ix_weather_observations_district'), table_name='weather_observations')
    op.drop_index('idx_weather_obs_time_station', table_name='weather_observations')
    op.drop_index('idx_weather_obs_geom', table_name='weather_observations', postgresql_using='gist')
    op.drop_index('idx_weather_obs_district', table_name='weather_observations')
    op.create_index(op.f('weather_observations_timestamp_utc_idx'), 'weather_observations', [sa.literal_column('timestamp_utc DESC')], unique=False)
    op.drop_index(op.f('ix_water_level_observations_timestamp_utc'), table_name='water_level_observations')
    op.drop_index(op.f('ix_water_level_observations_station_id'), table_name='water_level_observations')
    op.drop_index(op.f('ix_water_level_observations_river_name'), table_name='water_level_observations')
    op.drop_index(op.f('ix_water_level_observations_district'), table_name='water_level_observations')
    op.drop_index('idx_water_obs_time_station', table_name='water_level_observations')
    op.drop_index('idx_water_obs_alert', table_name='water_level_observations')
    op.create_index(op.f('water_level_observations_timestamp_utc_idx'), 'water_level_observations', [sa.literal_column('timestamp_utc DESC')], unique=False)
    op.drop_index(op.f('ix_stations_station_type'), table_name='stations')
    op.drop_index(op.f('ix_stations_station_id'), table_name='stations')
    op.drop_index(op.f('ix_stations_river_name'), table_name='stations')
    op.drop_index(op.f('ix_stations_major_basin'), table_name='stations')
    op.drop_index(op.f('ix_stations_district'), table_name='stations')
    op.drop_index(op.f('ix_soil_moisture_observations_timestamp_utc'), table_name='soil_moisture_observations')
    op.drop_index(op.f('ix_soil_moisture_observations_spatial_id'), table_name='soil_moisture_observations')
    op.drop_index('idx_soil_obs_time_spatial', table_name='soil_moisture_observations')
    op.drop_index('idx_soil_obs_geom', table_name='soil_moisture_observations', postgresql_using='gist')
    op.create_index(op.f('soil_moisture_observations_timestamp_utc_idx'), 'soil_moisture_observations', [sa.literal_column('timestamp_utc DESC')], unique=False)
    op.drop_index(op.f('ix_risk_decisions_station_id'), table_name='risk_decisions')
    op.drop_index(op.f('ix_risk_decisions_sample_type'), table_name='risk_decisions')
    op.drop_index(op.f('ix_risk_decisions_sample_id'), table_name='risk_decisions')
    op.drop_index(op.f('ix_risk_decisions_final_risk_class'), table_name='risk_decisions')
    op.drop_index(op.f('ix_risk_decisions_district'), table_name='risk_decisions')
    op.drop_index(op.f('ix_risk_decisions_alert_priority'), table_name='risk_decisions')
    op.create_unique_constraint(op.f('uq_risk_decisions_sample_id'), 'risk_decisions', ['timestamp_utc', 'sample_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('risk_decisions_timestamp_utc_idx'), 'risk_decisions', [sa.literal_column('timestamp_utc DESC')], unique=False)
    op.drop_index(op.f('ix_rainfall_observations_timestamp_utc'), table_name='rainfall_observations')
    op.drop_index(op.f('ix_rainfall_observations_spatial_id'), table_name='rainfall_observations')
    op.drop_index(op.f('ix_rainfall_observations_district'), table_name='rainfall_observations')
    op.drop_index('idx_rain_obs_time_spatial', table_name='rainfall_observations')
    op.drop_index('idx_rain_obs_geom', table_name='rainfall_observations', postgresql_using='gist')
    op.drop_index('idx_rain_obs_district', table_name='rainfall_observations')
    op.create_index(op.f('rainfall_observations_timestamp_utc_idx'), 'rainfall_observations', [sa.literal_column('timestamp_utc DESC')], unique=False)
    op.drop_index(op.f('ix_historical_flood_events_event_type'), table_name='historical_flood_events')
    op.drop_index(op.f('ix_historical_flood_events_event_id'), table_name='historical_flood_events')
    op.drop_index(op.f('ix_historical_flood_events_event_date'), table_name='historical_flood_events')
    op.drop_index(op.f('ix_historical_flood_events_district'), table_name='historical_flood_events')
    op.drop_index('idx_hist_events_geom', table_name='historical_flood_events', postgresql_using='gist')
    op.drop_index('idx_hist_events_district_type', table_name='historical_flood_events')
    op.drop_index(op.f('ix_flood_predictions_timestamp_utc'), table_name='flood_predictions')
    op.drop_index(op.f('ix_flood_predictions_spatial_id'), table_name='flood_predictions')
    op.drop_index(op.f('ix_flood_predictions_sample_type'), table_name='flood_predictions')
    op.drop_index(op.f('ix_flood_predictions_prediction_probability'), table_name='flood_predictions')
    op.drop_index(op.f('ix_flood_predictions_ml_risk_class'), table_name='flood_predictions')
    op.drop_index(op.f('ix_flood_predictions_district'), table_name='flood_predictions')
    op.drop_index('idx_predictions_time_spatial', table_name='flood_predictions')
    op.drop_index('idx_predictions_risk_district', table_name='flood_predictions')
    op.drop_index('idx_predictions_geom', table_name='flood_predictions', postgresql_using='gist')
    op.create_unique_constraint(op.f('uq_flood_predictions_sample_id'), 'flood_predictions', ['timestamp_utc', 'sample_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('flood_predictions_timestamp_utc_idx'), 'flood_predictions', [sa.literal_column('timestamp_utc DESC')], unique=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sachet_alerts_identifier'), table_name='sachet_alerts')
    op.drop_index(op.f('ix_sachet_alerts_id'), table_name='sachet_alerts')
    op.drop_index('idx_sachet_alerts_polygon', table_name='sachet_alerts', postgresql_using='gist')
    op.drop_table('sachet_alerts')
    # ### end Alembic commands ###
